run:
  skip-dirs:
    - harness/nextgen

output:
  format: colored-line-number

linters-settings:
  errcheck:
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)
