pipeline:
    stages:
        - stage:
              variables:
                  - name: HARNESS_API_KEY
                    type: Secret
                    value: org.harness_api_key
                  - name: HARNESS_ACCOUNT_ID
                    type: Secret
                    value: org.harness_account_id
                  - name: HARNESS_ENDPOINT
                    type: String
                    value: https://app.harness.io
                  - name: HARNESS_TEST_SPOT_ACCT_ID
                    type: Secret
                    value: org.spotinst_account_id
                  - name: HARNESS_TEST_SPOT_TOKEN
                    type: Secret
                    value: org.spotinst_token
                  - name: HARNESS_TEST_AZURE_CLIENT_ID
                    type: Secret
                    value: org.azure_client_id
                  - name: HARNESS_TEST_AZURE_CLIENT_SECRET
                    type: Secret
                    value: org.azure_client_secret
                  - name: HARNESS_TEST_AZURE_TENANT_ID
                    type: Secret
                    value: org.azure_tenant_id
                  - name: HARNESS_TEST_AWS_ACCESS_KEY_ID
                    type: Secret
                    value: org.aws_access_key_id
                  - name: HARNESS_TEST_AWS_SECRET_ACCESS_KEY
                    type: Secret
                    value: org.aws_secret_access_key
                  - name: HARNESS_TEST_DELEGATE_SECRET
                    type: Secret
                    value: org.harness_delegate_secret
                  - name: HARNESS_TEST_DELEGATE_PROFILE_ID
                    type: Secret
                    value: org.harness_delegate_profile_id
              type: CI
              spec:
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.micahsprojects
                          namespace: micahs-projects
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Wait for Docker Host
                                identifier: Wait_for_Docker_Host
                                spec:
                                    connectorRef: account.harnessImage
                                    image: docker:dind
                                    command: |-
                                        ls -la /var/run
                                        ls -la /var/lib/docker

                                        while ! docker ps ;do
                                            echo "Docker not availble yet"
                                            sleep 1s
                                        done
                                            echo "Docker Service Ready"

                                        ls -la /var/run
                                        ls -la /var/lib/docker
                                    privileged: false
                          - step:
                                type: Run
                                name: test
                                identifier: test
                                spec:
                                    connectorRef: account.harnessImage
                                    image: busybox:latest
                                    command: |
                                        ls -la /var/run
                                        ls -la /var/lib/docker
                                    privileged: false
                          - step:
                                type: RestoreCacheGCS
                                spec:
                                    resources:
                                        limits:
                                            memory: 1Gi
                                            cpu: "1"
                                    key: harness-go-sdk-{{ checksum "go.mod" }}
                                    connectorRef: org.gcp
                                    bucket: harness-micah-test
                                    archiveFormat: Gzip
                                name: Restore from cache
                                identifier: Restore_from_cache
                          - step:
                                type: Run
                                spec:
                                    privileged: false
                                    image: us.gcr.io/sales-209522/micah/go-build-tools:1.16-stretch-10
                                    connectorRef: org.gcp
                                    command: go mod vendor
                                name: Download modules
                                identifier: Download_modules
                          - step:
                                type: SaveCacheGCS
                                spec:
                                    sourcePaths:
                                        - ./vendor
                                    key: harness-go-sdk-{{ checksum "go.mod" }}
                                    connectorRef: org.gcp
                                    bucket: harness-micah-test
                                    archiveFormat: Gzip
                                name: Save cache
                                identifier: Save_cache
                          - parallel:
                                - step:
                                      type: Run
                                      spec:
                                          connectorRef: org.gcp
                                          image: us.gcr.io/sales-209522/micah/go-build-tools:1.16-stretch-10
                                          command: golangci-lint run -v
                                          privileged: false
                                          resources:
                                              limits:
                                                  memory: 2Gi
                                                  cpu: "1"
                                      name: Lint
                                      identifier: lint
                                - step:
                                      type: Run
                                      spec:
                                          connectorRef: org.gcp
                                          image: us.gcr.io/sales-209522/micah/go-build-tools:1.16-stretch-10
                                          command: gotestsum --junitfile junit.xml --format testname
                                          privileged: false
                                          reports:
                                              type: JUnit
                                              spec:
                                                  paths:
                                                      - junit.xml
                                          resources:
                                              limits:
                                                  memory: 2Gi
                                                  cpu: "2"
                                      name: Test
                                      identifier: Test
                  cloneCodebase: true
                  sharedPaths:
                      - /var/run
                      - /var/lib/docker
                  serviceDependencies:
                      - identifier: DockerHost
                        name: DockerHost
                        type: Service
                        spec:
                            connectorRef: account.harnessImage
                            image: docker:dind
                            privileged: true
                            resources:
                                limits:
                                    memory: 4Gi
                                    cpu: "1"
              name: Build
              identifier: Build
    properties:
        ci:
            codebase:
                repoName: harness-go-sdk
                connectorRef: org.githubharnessio
                build: <+input>
    projectIdentifier: harness_gos_dk
    orgIdentifier: Micahs_Projects
    name: ci
    identifier: ci
