pipeline:
    name: Release
    identifier: release
    projectIdentifier: harness_gos_dk
    orgIdentifier: Micahs_Projects
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: org.githubharnessio
                repoName: harness-go-sdk
                build: <+input>
    stages:
        - stage:
              name: Release
              identifier: Release
              description: ""
              type: CI
              spec:
                  cloneCodebase: true
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Prep release
                                identifier: Prep_release
                                spec:
                                    connectorRef: org.gcp
                                    image: us.gcr.io/sales-209522/micah/go-build-tools:1.16-stretch-9
                                    command: |
                                        sed -i.bak "s/SDKVersion = .*/SDKVersion = \"$version\"/"  harness/version.go && rm harness/version.go.bak
                                    privileged: false
                          - step:
                                type: Plugin
                                name: Generate changelog
                                identifier: Generate_changelog
                                spec:
                                    connectorRef: account.harnessImage
                                    image: naorlivne/drone-github-changelog-generator
                                    privileged: false
                                    settings:
                                        github_user: <+Create_Release.variables.GITHUB_OWNER>
                                        github_project: <+Create_Release.variables.GITHUB_REPO>
                          - step:
                                type: Plugin
                                name: Push changes
                                identifier: Push_changes
                                spec:
                                    connectorRef: account.harnessImage
                                    image: appleboy/drone-git-push
                                    privileged: false
                                    settings:
                                        remote_name: origin
                                        branch: release
                                        commit: "true"
                                        author_name: Harness CI
                                        author_email: harness-ci-automation@harness.io
                                        commit_message: Release v<+pipeline.stages.Create_Release.variables.VERSION>
                                        force: "true"
                          - step:
                                type: Run
                                name: Create release
                                identifier: Create_release
                                spec:
                                    connectorRef: org.gcp
                                    image: us.gcr.io/sales-209522/micah/go-build-tools:1.16-stretch
                                    command: |
                                        #!/bin/bash

                                        curl \
                                          -Ss \
                                          -X POST \
                                          -H "Accept: application/vnd.github.v3+json" \
                                          -H "Authorization: token ${GITHUB_TOKEN}" \
                                          https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/pulls \
                                          -d "{ \
                                            \"head\": \"release\", \
                                            \"base\": \"${BASE_BRANCH}\", \
                                            \"auto_merge\": true, \
                                            \"title\": \"Release version ${VERSION} $(date +%m-%d-%Y)\" \
                                          }" -o output.json

                                        PR_NUMBER=$(jq -s ".[0].number" output.json)

                                        curl \
                                          -Ss \
                                          -X PUT \
                                          -H "Accept: application/vnd.github.v3+json" \
                                          -H "Authorization: token ${GITHUB_TOKEN}" \
                                          https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/pulls/${PR_NUMBER}/merge \
                                          -d "{\"commit_title\":\"Release version ${VERSION} $(date +%m-%d-%Y)\"}"

                                        curl \
                                          -X POST \
                                          -H "Accept: application/vnd.github.v3+json" \
                                          -H "Authorization: token ${GITHUB_TOKEN}" \
                                          https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/releases \
                                          -d "{ \
                                            \"tag_name\": \"v${VERSION}\", \
                                            \"target_commitish\": \"${BASE_BRANCH}\"
                                          }"
                                    privileged: false
                                    envVariables:
                                        GITHUB_TOKEN: <+Create_Release.variables.CHANGELOG_GITHUB_TOKEN>
                  serviceDependencies: []
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.micahsprojects
                          namespace: micahs-projects
              variables:
                  - name: VERSION
                    type: String
                    value: <+input>
                  - name: CHANGELOG_GITHUB_TOKEN
                    type: Secret
                    value: org.githubciautomationtoken
                  - name: GITHUB_TOKEN
                    type: Secret
                    value: org.githubciautomationtoken
                  - name: GITHUB_OWNER
                    type: String
                    value: harness-io
                  - name: GITHUB_REPO
                    type: String
                    value: harness-go-sdk
                  - name: BASE_BRANCH
                    type: String
                    default: main
                    value: <+input>
