name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - name: asdf_install
      uses: asdf-vm/actions/install@v1.1.0

    - name: Build
      run: go build -v ./...
